### ISSUE TITLE
replace kafka with nats

### ISSUE THREAD

**Issue by josephakayesi** [kalecapital/auth#48]
at the moment we are using kafka as a queue. nats is more designed for message queues capabilities and therefore we need to replace kafka with nats. 

add nats ui to monitor messages in local development:
- [nats-streaming-console](https://github.com/KualiCo/nats-streaming-console?tab=readme-ov-file)
- [nats-streaming-ui](https://github.com/piotrpersona/nats-streaming-ui?tab=readme-ov-file)

also to learn something new :)

**Comment by josephakayesi** [comment]
Kafka config: 

```
version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network
    # volumes:
    #   - ./data/zk-data:/var/lib/zookeeper/data
    #   - ./data/zk-txn-logs:/var/lib/zookeeper/logs
    user: root

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
      - 19092:19092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: internal://kafka:9092,external://34.255.11.124:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    # volumes:
    #   - ./data/kafka-data:/var/lib/kafka/data
    user: root
  # dynamodb:
  #   image: "amazon/dynamodb-local:latest"
  #   container_name: dynamodb
  #   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - "./data/dynamodb:/home/dynamodblocal/data"
  #   working_dir: /home/dynamodblocal
  #   networks:
  #     - kafka-network
  #   mem_limit: 500m

networks:
  kafka-network:
    driver: bridge
```

```
ui:
	docker run -it -p 9080:8080 --name kafka-ui -e DYNAMIC_CONFIG_ENABLED=true --restart on-failure provectuslabs/kafka-ui 

ui-down:
	docker rm -f kafka-ui

dynamo:
	docker-compose -f docker-compose.dynamo.yml up
```
